language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=dev-master

sudo: false

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master

install:
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar

before_script:
    - nohup php -S localhost:8080 -t features/fixtures/project/web > server.log 2>&1 &
    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99.0
    - java -jar selenium-server-standalone-2.42.2.jar > /dev/null &
    - sleep 5

script:
    - composer self-update
    - composer require symfony/symfony:${SYMFONY_VERSION} -n --prefer-source
    - ./bin/phpspec run -v
    - ./bin/behat --no-snippets --no-paths --verbose --format=progress --profile=travis -vvv

after_failure:
    - cat server.log

notifications:
  irc:   "irc.freenode.org#fsi-open"
