language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*@dev
  - SYMFONY_VERSION=dev-master

sudo: false

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
    - env: SYMFONY_VERSION=2.8.*@dev
    - php: hhvm
  exclude:
    - env: SYMFONY_VERSION=dev-master
      php: 5.4
    - env: SYMFONY_VERSION=2.6.*
      php: 7.0

before_install:
    - composer self-update
    - composer require symfony/symfony:${SYMFONY_VERSION} -n --prefer-source

install:
    - wget http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar

before_script:
    - nohup php -S localhost:8080 -t features/fixtures/project/web > server.log 2>&1 &
    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99.0
    - java -jar selenium-server-standalone-2.47.1.jar > /dev/null &
    - sleep 5
    - features/fixtures/project/app/console assets:install features/fixtures/project/web --relative --symlink

script:
    - ./bin/phpspec run -v
    - ./bin/behat --no-snippets --verbose --format=progress --profile=travis -v

after_failure:
    - cat server.log

notifications:
  irc:   "irc.freenode.org#fsi-open"
