language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer --prefer-source -n update

script:
  - ./bin/phpspec run -f pretty
  - ./bin/behat --no-snippets --no-paths --verbose --format=progress
