language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*@dev
  - SYMFONY_VERSION=dev-master

sudo: false

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=2.7.*@dev
    - env: SYMFONY_VERSION=dev-master
    - php: 7.0
    - php: hhvm
  exclude:
    - env: SYMFONY_VERSION=dev-master
      php: 5.4

install:
    - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar

before_script:
    - nohup php -S localhost:8080 -t features/fixtures/project/web > server.log 2>&1 &
    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99.0
    - java -jar selenium-server-standalone-2.42.2.jar > /dev/null &
    - sleep 5
    - mkdir -p features/fixtures/project/web/bundles/fsiadmin
    - cp Resources/public/* features/fixtures/project/web/bundles/fsiadmin

script:
    - composer self-update
    - composer require symfony/symfony:${SYMFONY_VERSION} -n --prefer-source
    - ./bin/phpspec run -v
    - ./bin/behat --no-snippets --no-paths --verbose --format=progress --profile=travis -vvv

after_failure:
    - cat server.log

notifications:
  irc:   "irc.freenode.org#fsi-open"
